In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

In [25]:
import keras
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.


In [15]:
df=pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [17]:
df.shape

(10000, 14)

In [18]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [20]:
#df.dtypes

In [21]:
X = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values

In [22]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [24]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [26]:
# Initialising the ANN
classifier = Sequential()

In [29]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 1, init = "uniform", activation="sigmoid"))

In [30]:
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [31]:
classifier.fit(X_train, y_train, batch_size=10, nb_epoch= 100)

Epoch 1/100
8000/8000 [==============================] - 5s 654us/step - loss: 0.5635 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 3s 387us/step - loss: 0.5062 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 3s 319us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 267us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 305us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 3s 334us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 3s 405us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 2s 295us/step - loss: 0.5059 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 3s 317us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 10/100
8000/8000 [==============================]

Epoch 77/100
8000/8000 [==============================] - 3s 335us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 78/100
8000/8000 [==============================] - 3s 339us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 79/100
8000/8000 [==============================] - 3s 383us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 80/100
8000/8000 [==============================] - 3s 357us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 81/100
8000/8000 [==============================] - 4s 447us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 82/100
8000/8000 [==============================] - 4s 461us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 83/100
8000/8000 [==============================] - 3s 401us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 84/100
8000/8000 [==============================] - 3s 335us/step - loss: 0.5061 - accuracy: 0.7960
Epoch 85/100
8000/8000 [==============================] - 2s 285us/step - loss: 0.5060 - accuracy: 0.7960
Epoch 86/100
8000/8000 [======================

In [32]:
y_pred = classifier.predict(X_test)
y_pred

array([[0.20246774],
       [0.20246774],
       [0.20246774],
       ...,
       [0.20246774],
       [0.20246774],
       [0.20246774]], dtype=float32)

In [33]:
y_pred = (y_pred > 0.5)

In [38]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [39]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [40]:
cm

array([[1595,    0],
       [ 405,    0]], dtype=int64)